spring.application.name=ChatbotBackend

# --- Banco de Dados (Mantido do MVP) ---
spring.datasource.url=jdbc:mysql://localhost:3306/teste_squad8
spring.datasource.username=root
spring.datasource.password=2208
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Token de Acesso
whatsapp.token=EAATH4SoJeZAEBQL345IABw6m70rWASelZCiu1ZAlJIZAgmFoYgWPBMXQ75J6OB2DswrEG9b9SuXYum2W4O1K2VrhSUJzWMAcJSYfVJGz2L12GGHuq4cFiZCUc1m80AqT8zi3oU1u6zllRTZA9K2T4UY0nknTHt0tyr0EjcFA3MyBBXabXO3KyZAWdtZCdVmLT0bxSwhYj6TkuZB0UwMaZAEwUTRDhMoQQGH93uqXcZALV9rlsUOHXuAH6AqooZCeNA7Qs38lZBzdjWt1OkpuGVCypNlU749Gz
# ID do Número de Telefone
whatsapp.phone-number-id=820662357796541
# Token que VOCÊ inventa para validar o Webhook
whatsapp.verify-token=TESTE_WEBHOOK
whatsapp.api-url=https://graph.facebook.com/v22.0

# Configuração Omie
omie.app-key=5614700718627
omie.app-secret=2ae8328ce879960d99ba83e7986805a3
omie.api-url=https://app.omie.com.br/api/v1

server.port=3000