spring.application.name=ChatbotBackend

spring.datasource.url=jdbc:mysql://localhost:3306/teste_squad8
spring.datasource.username=root
spring.datasource.password=1010
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

