spring.application.name=ChatbotBackend

# --- Banco de Dados (Mantido do MVP) ---
spring.datasource.url=jdbc:mysql://localhost:3306/teste_squad8
spring.datasource.username=root
spring.datasource.password=2208
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Token de Acesso
whatsapp.token=EAATH4SoJeZAEBQOIoxPnwa2fmyzw33Q4SZCH0IDYhFaEcpufCJLNm6aA51lxNSh6JKemLgOLLSow0wCjmZCIdetsD8gH5C9ZB3dA1W7ndbMwZCuPPr6277bq6G3ncgyHdxFSX29TUbZC35TNvoZCNkFt3LPezLbXRDIY6cFaZCC3S1kMJrjgh0qkZAsci60ChxGYzqYczCwzz98nbHwuWPhAgt7MsRVzDzw5SI5YR3mj6LFOb7Ce5lJg1dl4lKjUq9gMufZC0sIgHZCJns45VDIt04NFebj
# ID do Número de Telefone
whatsapp.phone-number-id=820662357796541
# Token que VOCÊ inventa para validar o Webhook
whatsapp.verify-token=TESTE_WEBHOOK
whatsapp.api-url=https://graph.facebook.com/v22.0

# Configuração Omie
omie.app-key=5614700718627
omie.app-secret=2ae8328ce879960d99ba83e7986805a3
omie.api-url=https://app.omie.com.br/api/v1

server.port=3000