spring.application.name=ChatbotBackend

spring.datasource.url=jdbc:mysql://localhost:3306/teste_squad8
spring.datasource.username=root
spring.datasource.password=1010
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

whatsapp.phone-number-id=820662357796541
whatsapp.token=EAATH4SoJeZAEBPxMh2pb8KMqaggfCZBE56tgPIaLR6sS9IMaM0OqmNZAlLgdkCJecs1aR3tUy2KQPmG9PmwrInXPpAiMT1HrBbYlqfhaHuVSKZBlhBH6YLnqFP5NWE39unVzxmgANpVnVeSXMn7ecOZBLavo2EqIfRoilAUPC9mWhntk5WZBAUzox61iv2ruW7RgZDZD
server.port=8080

